// <auto-generated />
using System;
using DoAn.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAn.Migrations
{
    [DbContext(typeof(ModelContext))]
    partial class ModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.Property<int>("ActorsActorId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesMovieId")
                        .HasColumnType("int");

                    b.HasKey("ActorsActorId", "MoviesMovieId");

                    b.HasIndex("MoviesMovieId");

                    b.ToTable("ActorMovie");
                });

            modelBuilder.Entity("DirectorMovie", b =>
                {
                    b.Property<int>("DirectorsDirectorId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesMovieId")
                        .HasColumnType("int");

                    b.HasKey("DirectorsDirectorId", "MoviesMovieId");

                    b.HasIndex("MoviesMovieId");

                    b.ToTable("DirectorMovie");
                });

            modelBuilder.Entity("DoAn.Models.Accounts.Membership", b =>
                {
                    b.Property<int>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("membership_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembershipId"));

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.Property<int?>("TierId")
                        .HasColumnType("int")
                        .HasColumnName("tier_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("MembershipId");

                    b.HasIndex("TierId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("DoAn.Models.Accounts.MembershipTier", b =>
                {
                    b.Property<int>("TierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tier_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TierId"));

                    b.Property<int>("MaxPoints")
                        .HasColumnType("int")
                        .HasColumnName("max_points");

                    b.Property<int>("MinPoints")
                        .HasColumnType("int")
                        .HasColumnName("min_points");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("tier_name");

                    b.HasKey("TierId");

                    b.HasIndex("TierName")
                        .IsUnique();

                    b.ToTable("membership_tiers", (string)null);
                });

            modelBuilder.Entity("DoAn.Models.Accounts.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("PermissionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("DoAn.Models.Accounts.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uni_users_email");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("uni_users_phone");

                    b.HasIndex("RoleId");

                    b.ToTable("users", null, t =>
                        {
                            t.HasTrigger("trg_create_membership");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("DoAn.Models.Accounts.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("DoAn.Models.Accounts.UserRolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserRolePermissions");
                });

            modelBuilder.Entity("DoAn.Models.Booking.ComboItem", b =>
                {
                    b.Property<int>("ComboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("combo_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.HasKey("ComboId");

                    b.ToTable("combo_items", (string)null);
                });

            modelBuilder.Entity("DoAn.Models.Booking.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("promotion_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionId"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("DiscountType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("discount_type");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("value");

                    b.HasKey("PromotionId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uni_promotions_code")
                        .HasFilter("[code] IS NOT NULL");

                    b.ToTable("promotions", (string)null);
                });

            modelBuilder.Entity("DoAn.Models.Booking.Showtime", b =>
                {
                    b.Property<int>("ShowtimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("showtime_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShowtimeId"));

                    b.Property<decimal?>("BasePrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("base_price");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("end_time");

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("start_time");

                    b.HasKey("ShowtimeId");

                    b.HasIndex("RoomId");

                    b.HasIndex("MovieId", "RoomId", "StartTime")
                        .IsUnique()
                        .HasDatabaseName("uni_showtimes")
                        .HasFilter("[start_time] IS NOT NULL");

                    b.ToTable("showtimes", (string)null);
                });

            modelBuilder.Entity("DoAn.Models.Booking.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<DateTime?>("BookingTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("booking_time");

                    b.Property<int>("SeatId")
                        .HasColumnType("int")
                        .HasColumnName("seat_id");

                    b.Property<int>("ShowtimeId")
                        .HasColumnType("int")
                        .HasColumnName("showtime_id");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("TicketId");

                    b.HasIndex("SeatId");

                    b.HasIndex("ShowtimeId");

                    b.HasIndex("UserId");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("DoAn.Models.Booking.TicketCombo", b =>
                {
                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("ComboId")
                        .HasColumnType("int");

                    b.Property<short?>("Quantity")
                        .HasColumnType("smallint");

                    b.HasKey("TicketId", "ComboId");

                    b.HasIndex("ComboId");

                    b.ToTable("ticket_combos", (string)null);
                });

            modelBuilder.Entity("DoAn.Models.Booking.TicketPriceHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("ChangedBy")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("ChangedBy");

                    b.Property<int>("ChangedByUserUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("NewPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("OldPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ShowtimeId")
                        .HasColumnType("int");

                    b.HasKey("HistoryId");

                    b.HasIndex("ChangedByUserUserId");

                    b.HasIndex("ShowtimeId");

                    b.ToTable("ticket_price_history", (string)null);
                });

            modelBuilder.Entity("DoAn.Models.Cinema.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("branch_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("phone");

                    b.HasKey("BranchId");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasDatabaseName("uni_branches_address")
                        .HasFilter("[address] IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("uni_branches_phone")
                        .HasFilter("[phone] IS NOT NULL");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("DoAn.Models.Cinema.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("branch_id");

                    b.Property<short?>("Capacity")
                        .HasColumnType("smallint")
                        .HasColumnName("capacity");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("RoomTypeId")
                        .HasColumnType("int")
                        .HasColumnName("room_type_id");

                    b.HasKey("RoomId");

                    b.HasIndex("BranchId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("DoAn.Models.Cinema.RoomType", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("room_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("base_price");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("type_name");

                    b.HasKey("RoomTypeId");

                    b.HasIndex("TypeName")
                        .IsUnique()
                        .HasDatabaseName("uni_room_type_name");

                    b.ToTable("room_types", (string)null);
                });

            modelBuilder.Entity("DoAn.Models.Cinema.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("seat_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<short?>("SeatNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("seat_number");

                    b.Property<string>("SeatRow")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("seat_row");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.HasKey("SeatId");

                    b.HasIndex("TypeId");

                    b.HasIndex("RoomId", "SeatRow", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("uni_seats")
                        .HasFilter("[seat_row] IS NOT NULL AND [seat_number] IS NOT NULL");

                    b.ToTable("seats", (string)null);
                });

            modelBuilder.Entity("DoAn.Models.Cinema.SeatType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<decimal?>("ExtraPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("extra_price");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("TypeId");

                    b.ToTable("seat_types", (string)null);
                });

            modelBuilder.Entity("DoAn.Models.Movies.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("actor_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActorId"));

                    b.Property<string>("ActorName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("actor_name");

                    b.HasKey("ActorId");

                    b.ToTable("actors", (string)null);
                });

            modelBuilder.Entity("DoAn.Models.Movies.AgeRating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rating_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("RatingCode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("rating_code");

                    b.HasKey("RatingId");

                    b.HasIndex("RatingCode")
                        .IsUnique()
                        .HasDatabaseName("uni_age_ratings")
                        .HasFilter("[rating_code] IS NOT NULL");

                    b.ToTable("age_ratings", (string)null);
                });

            modelBuilder.Entity("DoAn.Models.Movies.Director", b =>
                {
                    b.Property<int>("DirectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("director_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DirectorId"));

                    b.Property<string>("DirectorName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("director_name");

                    b.HasKey("DirectorId");

                    b.ToTable("directors", (string)null);
                });

            modelBuilder.Entity("DoAn.Models.Movies.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cover_url");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("genre");

                    b.Property<decimal?>("ImdbRating")
                        .HasColumnType("decimal(3,1)")
                        .HasColumnName("imdb_rating");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("poster_url");

                    b.Property<int?>("RatingId")
                        .HasColumnType("int")
                        .HasColumnName("rating_id");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trailer_url");

                    b.HasKey("MovieId");

                    b.HasIndex("RatingId");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("DoAn.Models.Movies.MovieActor", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    b.Property<int>("ActorId")
                        .HasColumnType("int")
                        .HasColumnName("actor_id");

                    b.Property<int?>("MovieActorActorId")
                        .HasColumnType("int");

                    b.Property<int?>("MovieActorMovieId")
                        .HasColumnType("int");

                    b.Property<int?>("MovieDirectorDirectorId")
                        .HasColumnType("int");

                    b.Property<int?>("MovieDirectorMovieId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.HasIndex("MovieActorMovieId", "MovieActorActorId");

                    b.HasIndex("MovieDirectorMovieId", "MovieDirectorDirectorId");

                    b.ToTable("movie_actors", (string)null);
                });

            modelBuilder.Entity("DoAn.Models.Movies.MovieDirector", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int")
                        .HasColumnName("director_id");

                    b.HasKey("MovieId", "DirectorId");

                    b.HasIndex("DirectorId");

                    b.ToTable("movie_directors", (string)null);
                });

            modelBuilder.Entity("DoAn.Models.Payments.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("method");

                    b.Property<DateTime?>("PaymentTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_time");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int")
                        .HasColumnName("promotion_id");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("transaction_id");

                    b.HasKey("PaymentId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("TicketId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.HasOne("DoAn.Models.Movies.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorsActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn.Models.Movies.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DirectorMovie", b =>
                {
                    b.HasOne("DoAn.Models.Movies.Director", null)
                        .WithMany()
                        .HasForeignKey("DirectorsDirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn.Models.Movies.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoAn.Models.Accounts.Membership", b =>
                {
                    b.HasOne("DoAn.Models.Accounts.MembershipTier", "MembershipTier")
                        .WithMany("Memberships")
                        .HasForeignKey("TierId");

                    b.HasOne("DoAn.Models.Accounts.User", "User")
                        .WithOne("Membership")
                        .HasForeignKey("DoAn.Models.Accounts.Membership", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembershipTier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoAn.Models.Accounts.User", b =>
                {
                    b.HasOne("DoAn.Models.Accounts.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_users_roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DoAn.Models.Accounts.UserRolePermission", b =>
                {
                    b.HasOne("DoAn.Models.Accounts.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_permissions_permissions");

                    b.HasOne("DoAn.Models.Accounts.UserRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_permissions_roles");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DoAn.Models.Booking.Showtime", b =>
                {
                    b.HasOne("DoAn.Models.Movies.Movie", "Movie")
                        .WithMany("Showtimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn.Models.Cinema.Room", "Room")
                        .WithMany("Showtimes")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DoAn.Models.Booking.Ticket", b =>
                {
                    b.HasOne("DoAn.Models.Cinema.Seat", "Seat")
                        .WithMany("Tickets")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn.Models.Booking.Showtime", "Showtime")
                        .WithMany("Tickets")
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn.Models.Accounts.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId");

                    b.Navigation("Seat");

                    b.Navigation("Showtime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoAn.Models.Booking.TicketCombo", b =>
                {
                    b.HasOne("DoAn.Models.Booking.ComboItem", "ComboItem")
                        .WithMany("TicketCombos")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn.Models.Booking.Ticket", "Ticket")
                        .WithMany("TicketCombos")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComboItem");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("DoAn.Models.Booking.TicketPriceHistory", b =>
                {
                    b.HasOne("DoAn.Models.Accounts.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn.Models.Booking.Showtime", "Showtime")
                        .WithMany()
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Showtime");
                });

            modelBuilder.Entity("DoAn.Models.Cinema.Room", b =>
                {
                    b.HasOne("DoAn.Models.Cinema.Branch", "Branch")
                        .WithMany("Rooms")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn.Models.Cinema.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId");

                    b.Navigation("Branch");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("DoAn.Models.Cinema.Seat", b =>
                {
                    b.HasOne("DoAn.Models.Cinema.Room", "Room")
                        .WithMany("Seats")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn.Models.Cinema.SeatType", "SeatType")
                        .WithMany("Seats")
                        .HasForeignKey("TypeId");

                    b.Navigation("Room");

                    b.Navigation("SeatType");
                });

            modelBuilder.Entity("DoAn.Models.Movies.Movie", b =>
                {
                    b.HasOne("DoAn.Models.Movies.AgeRating", "AgeRating")
                        .WithMany("Movies")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AgeRating");
                });

            modelBuilder.Entity("DoAn.Models.Movies.MovieActor", b =>
                {
                    b.HasOne("DoAn.Models.Movies.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn.Models.Movies.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn.Models.Movies.MovieActor", null)
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieActorMovieId", "MovieActorActorId");

                    b.HasOne("DoAn.Models.Movies.MovieDirector", null)
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieDirectorMovieId", "MovieDirectorDirectorId");

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("DoAn.Models.Movies.MovieDirector", b =>
                {
                    b.HasOne("DoAn.Models.Movies.Director", "Director")
                        .WithMany("MovieDirectors")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn.Models.Movies.Movie", "Movie")
                        .WithMany("MovieDirectors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("DoAn.Models.Payments.Payment", b =>
                {
                    b.HasOne("DoAn.Models.Booking.Promotion", "Promotion")
                        .WithMany("Payments")
                        .HasForeignKey("PromotionId");

                    b.HasOne("DoAn.Models.Booking.Ticket", "Ticket")
                        .WithMany("Payments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("DoAn.Models.Accounts.MembershipTier", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("DoAn.Models.Accounts.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("DoAn.Models.Accounts.User", b =>
                {
                    b.Navigation("Membership")
                        .IsRequired();

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("DoAn.Models.Accounts.UserRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DoAn.Models.Booking.ComboItem", b =>
                {
                    b.Navigation("TicketCombos");
                });

            modelBuilder.Entity("DoAn.Models.Booking.Promotion", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DoAn.Models.Booking.Showtime", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("DoAn.Models.Booking.Ticket", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("TicketCombos");
                });

            modelBuilder.Entity("DoAn.Models.Cinema.Branch", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DoAn.Models.Cinema.Room", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("DoAn.Models.Cinema.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DoAn.Models.Cinema.Seat", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("DoAn.Models.Cinema.SeatType", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("DoAn.Models.Movies.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("DoAn.Models.Movies.AgeRating", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("DoAn.Models.Movies.Director", b =>
                {
                    b.Navigation("MovieDirectors");
                });

            modelBuilder.Entity("DoAn.Models.Movies.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("MovieDirectors");

                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("DoAn.Models.Movies.MovieActor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("DoAn.Models.Movies.MovieDirector", b =>
                {
                    b.Navigation("MovieActors");
                });
#pragma warning restore 612, 618
        }
    }
}
